/*
 * This code was generated by FormatTemplate as part of the build process. Do not edit it.
 *
 * Generated on 2012-09-20 01:00:34.
 *
 */

namespace IronLua
{
    public static partial class CurrentVersion 
    {
        public const int Major = 0;
        public const int Minor = 1;
        public const int Micro = 0;
        public const string ReleaseLevel = "alpha";
        public const int ReleaseSerial = 0;

        public const string ShortReleaseLevel = "a";

        public const string Series = "0.1";
        public const string DisplayVersion = "0.1.0a0";
        public const string DisplayName = "IronLua 0.1.0a0";

#if !SILVERLIGHT
        public const string AssemblyVersion = "0.1.0.0";
#else
        public const string AssemblyVersion = "0.1.1300.0";
#endif
        
        public const string AssemblyFileVersion = "0.1.0.0000";
        public const string AssemblyInformationalVersion = "IronLua 0.1.0 alpha 0";
    }
}
